# Generated by Django 2.2.3 on 2019-09-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_password', models.CharField(max_length=10, verbose_name='參加密碼')),
                ('attend_number', models.IntegerField(default=0, verbose_name='參加人數')),
                ('attend_people', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='參加的人')),
            ],
            options={
                'verbose_name': '高中公開觀課報名人數',
                'verbose_name_plural': '高中公開觀課報名人數',
            },
        ),
        migrations.CreateModel(
            name='Design_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='單元名稱')),
                ('teach_teacher', models.CharField(max_length=6, verbose_name='授課老師')),
                ('source_of_teaching_material', models.CharField(max_length=20, verbose_name='教材來源')),
                ('teach_class', models.CharField(max_length=20, verbose_name='授課班級')),
                ('teach_date', models.DateField(verbose_name='教學日期')),
                ('teach_start_time', models.TimeField(verbose_name='教學開始時間')),
                ('teach_end_time', models.TimeField(verbose_name='教學結束時間')),
                ('background_analysis', models.TextField(verbose_name='學生學習背景分析')),
                ('teaching_method', models.TextField(verbose_name='教學方法')),
                ('teaching_resources', models.TextField(verbose_name='教學資源')),
                ('reference_material', models.TextField(verbose_name='參考資料')),
                ('teaching_objectives', models.TextField(verbose_name='教學目標')),
            ],
            options={
                'verbose_name': '高中課程教學活動設計表',
                'verbose_name_plural': '高中課程教學活動設計表',
            },
        ),
        migrations.CreateModel(
            name='High_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='上課科目')),
                ('class_room', models.CharField(max_length=10, verbose_name='上課教室')),
                ('teach_date', models.DateField(verbose_name='上課日期')),
                ('teach_start_time', models.TimeField(verbose_name='上課開始時間')),
                ('teach_end_time', models.TimeField(verbose_name='上課結束時間')),
                ('teaching_photo', models.URLField(default='', verbose_name='上課照片')),
                ('attend_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='the_class', to='public_class_high.Attend_data', verbose_name='參加資料')),
                ('teach_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='老師')),
            ],
            options={
                'verbose_name': '高中公開觀課報名資料',
                'verbose_name_plural': '高中公開觀課報名資料',
            },
        ),
        migrations.CreateModel(
            name='Preparation_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='學科')),
                ('author', models.CharField(max_length=6, verbose_name='填寫者')),
                ('teach_date', models.DateField(verbose_name='教學日期')),
                ('teach_start_time', models.TimeField(verbose_name='教學開始時間')),
                ('teach_end_time', models.TimeField(verbose_name='教學結束時間')),
                ('teaching_grade', models.CharField(max_length=20, verbose_name='教學年級')),
                ('class_name', models.CharField(max_length=20, verbose_name='教學單元')),
                ('teach_teacher', models.CharField(max_length=6, verbose_name='教學者')),
                ('source_of_teaching_material', models.CharField(max_length=20, verbose_name='教材來源')),
                ('content', models.TextField(verbose_name='教材內容')),
                ('teaching_objectives', models.TextField(verbose_name='教學目標')),
                ('student_experience', models.TextField(verbose_name='學生經驗')),
                ('teaching_activity', models.TextField(verbose_name='教學活動')),
                ('evaluation_method', models.TextField(verbose_name='學生學習成效評估方式')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程')),
            ],
            options={
                'verbose_name': '高中共同備課記錄表',
                'verbose_name_plural': '高中共同備課記錄表',
            },
        ),
        migrations.CreateModel(
            name='Observation_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='觀課日期')),
                ('teach_teacher', models.CharField(max_length=6, verbose_name='教學者')),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('class_name', models.CharField(max_length=20, verbose_name='單元名稱')),
                ('learning_atmosphere', models.TextField(verbose_name='全班學習氣氛')),
                ('learning_process', models.TextField(verbose_name='學生學習歷程')),
                ('learning_result', models.TextField(verbose_name='學生學習結果')),
                ('experience_and_learning', models.TextField(verbose_name='觀課的心得與學習')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='觀課者姓名')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程')),
            ],
            options={
                'verbose_name': '高中公開觀課紀錄表',
                'verbose_name_plural': '高中公開觀課紀錄表',
            },
        ),
        migrations.CreateModel(
            name='Design_table_datail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_objectives', models.TextField(verbose_name='教學目標')),
                ('teacher_activity', models.TextField(verbose_name='教師活動')),
                ('student_activities', models.TextField(verbose_name='學生活動')),
                ('teaching_aid', models.TextField(verbose_name='使用教具')),
                ('assessment_method', models.TextField(verbose_name='評量方式')),
                ('teaching_method', models.TextField(verbose_name='教學方法')),
                ('time_allocation', models.TextField(verbose_name='時間分配')),
                ('the_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.Design_table', verbose_name='課程教學活動設計表')),
            ],
            options={
                'verbose_name': '高中課程教學活動設計表下方表格',
                'verbose_name_plural': '高中課程教學活動設計表下方表格',
            },
        ),
        migrations.AddField(
            model_name='design_table',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程'),
        ),
        migrations.CreateModel(
            name='Briefing_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_teacher', models.CharField(max_length=6, verbose_name='教學者')),
                ('observer', models.TextField(verbose_name='觀察者')),
                ('briefing_date', models.DateField(verbose_name='議課日期')),
                ('briefing_time', models.TimeField(verbose_name='議課時間')),
                ('affirmation_teaching_performance', models.TextField(verbose_name='肯定教學表現')),
                ('guide_discussion_teaching_performance', models.TextField(verbose_name='引導討論教學表現')),
                ('judgment_performance', models.TextField(verbose_name='判斷表現程度')),
                ('suggest', models.TextField(verbose_name='改進學生學習能力提供之建議')),
                ('growth_activity', models.TextField(verbose_name='協助擬定成長活動')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程')),
            ],
            options={
                'verbose_name': '高中共同議課紀錄表',
                'verbose_name_plural': '高中共同議課紀錄表',
            },
        ),
    ]
