# Generated by Django 2.2.3 on 2019-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_class',
            name='teaching_photo',
            field=models.URLField(blank=True, default='', verbose_name='上課照片'),
        ),
    ]
