# Generated by Django 2.2.3 on 2019-07-23 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing_record',
            options={'verbose_name': '高中共同議課紀錄表', 'verbose_name_plural': '高中共同議課紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='design_table',
            options={'verbose_name': '高中課程教學活動設計表', 'verbose_name_plural': '高中課程教學活動設計表'},
        ),
        migrations.AlterModelOptions(
            name='design_table_datail',
            options={'verbose_name': '高中課程教學活動設計表下方表格', 'verbose_name_plural': '高中課程教學活動設計表下方表格'},
        ),
        migrations.AlterModelOptions(
            name='high_class',
            options={'verbose_name': '高中公開觀課報名資料', 'verbose_name_plural': '高中公開觀課報名資料'},
        ),
        migrations.AlterModelOptions(
            name='observation_record',
            options={'verbose_name': '高中公開觀課紀錄表', 'verbose_name_plural': '高中公開觀課紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='preparation_record',
            options={'verbose_name': '高中共同備課記錄表', 'verbose_name_plural': '高中共同備課記錄表'},
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='affirmation_teaching_performance',
            field=models.TextField(verbose_name='肯定教學表現'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='briefing_date',
            field=models.DateField(verbose_name='議課日期'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='briefing_time',
            field=models.TimeField(verbose_name='議課時間'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='growth_activity',
            field=models.TextField(verbose_name='協助擬定成長活動'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='guide_discussion_teaching_performance',
            field=models.TextField(verbose_name='引導討論教學表現'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='judgment_performance',
            field=models.TextField(verbose_name='判斷表現程度'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='observer',
            field=models.TextField(verbose_name='觀察者'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='suggest',
            field=models.TextField(verbose_name='改進學生學習能力提供之建議'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='background_analysis',
            field=models.TextField(verbose_name='學生學習背景分析'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='單元名稱'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='reference_material',
            field=models.TextField(verbose_name='參考資料'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='source_of_teaching_material',
            field=models.CharField(max_length=20, verbose_name='教材來源'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_class',
            field=models.CharField(max_length=20, verbose_name='授課班級'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_date',
            field=models.DateField(verbose_name='教學日期'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_end_time',
            field=models.TimeField(verbose_name='教學結束時間'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_start_time',
            field=models.TimeField(verbose_name='教學開始時間'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='授課老師'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teaching_method',
            field=models.TextField(verbose_name='教學方法'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teaching_objectives',
            field=models.TextField(verbose_name='教學目標'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teaching_resources',
            field=models.TextField(verbose_name='教學資源'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='assessment_method',
            field=models.TextField(verbose_name='評量方式'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='student_activities',
            field=models.TextField(verbose_name='學生活動'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teacher_activity',
            field=models.TextField(verbose_name='教師活動'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_aid',
            field=models.TextField(verbose_name='使用教具'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_method',
            field=models.TextField(verbose_name='教學方法'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_objectives',
            field=models.TextField(verbose_name='教學目標'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='the_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.Design_table', verbose_name='課程教學活動設計表'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='time_allocation',
            field=models.TextField(verbose_name='時間分配'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='attend_number',
            field=models.IntegerField(default=0, verbose_name='參加人數'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='attend_password',
            field=models.CharField(max_length=10, verbose_name='參加密碼'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='attend_people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='參加的人'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='class_room',
            field=models.CharField(max_length=10, verbose_name='上課教室'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='上課科目'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_date',
            field=models.DateField(verbose_name='上課日期'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_end_time',
            field=models.TimeField(verbose_name='上課結束時間'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_start_time',
            field=models.TimeField(verbose_name='上課開始時間'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='老師名字'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_teacher_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='老師信箱'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='author',
            field=models.CharField(max_length=6, verbose_name='觀課者姓名'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='單元名稱'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='experience_and_learning',
            field=models.TextField(verbose_name='觀課的心得與學習'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_atmosphere',
            field=models.TextField(verbose_name='全班學習氣氛'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_process',
            field=models.TextField(verbose_name='學生學習歷程'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_result',
            field=models.TextField(verbose_name='學生學習結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='observation_date',
            field=models.DateField(verbose_name='觀課日期'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='author',
            field=models.CharField(max_length=6, verbose_name='填寫者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='教學單元'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='content',
            field=models.TextField(verbose_name='教材內容'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='evaluation_method',
            field=models.TextField(verbose_name='學生學習成效評估方式'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='source_of_teaching_material',
            field=models.CharField(max_length=20, verbose_name='教材來源'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='student_experience',
            field=models.TextField(verbose_name='學生經驗'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='學科'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_date',
            field=models.DateField(verbose_name='教學日期'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_end_time',
            field=models.TimeField(verbose_name='教學結束時間'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_start_time',
            field=models.TimeField(verbose_name='教學開始時間'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_activity',
            field=models.TextField(verbose_name='教學活動'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_grade',
            field=models.CharField(max_length=20, verbose_name='教學年級'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_objectives',
            field=models.TextField(verbose_name='教學目標'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_high.High_Class', verbose_name='課程'),
        ),
    ]
