# Generated by Django 2.2.3 on 2019-07-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0002_auto_20190723_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing_record',
            name='teach_teacher_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='教學者信箱'),
        ),
        migrations.AddField(
            model_name='design_table',
            name='teach_teacher_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='授課老師信箱'),
        ),
        migrations.AddField(
            model_name='observation_record',
            name='author_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='觀課者信箱'),
        ),
        migrations.AddField(
            model_name='preparation_record',
            name='teach_teacher_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='教學者信箱'),
        ),
    ]
