# Generated by Django 2.2.3 on 2019-07-23 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0003_auto_20190723_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing_record',
            name='teach_teacher_email',
        ),
        migrations.RemoveField(
            model_name='design_table',
            name='teach_teacher_email',
        ),
        migrations.RemoveField(
            model_name='observation_record',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='preparation_record',
            name='teach_teacher_email',
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='觀課者姓名'),
        ),
    ]
