# Generated by Django 2.2.13 on 2020-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0003_auto_20190924_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing_record',
            name='teach_teacher',
            field=models.CharField(max_length=20, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='class_name',
            field=models.CharField(max_length=200, verbose_name='單元名稱'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='source_of_teaching_material',
            field=models.CharField(max_length=200, verbose_name='教材來源'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_class',
            field=models.CharField(max_length=200, verbose_name='授課班級'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_teacher',
            field=models.CharField(max_length=200, verbose_name='授課老師'),
        ),
        migrations.AlterField(
            model_name='high_class',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='上課科目'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='class_name',
            field=models.CharField(max_length=200, verbose_name='單元名稱'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teach_teacher',
            field=models.CharField(max_length=20, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='author',
            field=models.CharField(max_length=200, verbose_name='填寫者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='class_name',
            field=models.CharField(max_length=200, verbose_name='教學單元'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='source_of_teaching_material',
            field=models.CharField(max_length=200, verbose_name='教材來源'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='學科'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_teacher',
            field=models.CharField(max_length=20, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_grade',
            field=models.CharField(max_length=200, verbose_name='教學年級'),
        ),
    ]
