# Generated by Django 2.2.24 on 2021-09-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0004_auto_20200831_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Able_Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='default', max_length=100, verbose_name='模式')),
                ('able', models.BooleanField(default=True, verbose_name='開放註冊課程')),
            ],
        ),
    ]
