# Generated by Django 2.2.3 on 2019-07-23 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_class_high', '0004_auto_20190723_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='high_class',
            name='attend_number',
        ),
        migrations.RemoveField(
            model_name='high_class',
            name='attend_password',
        ),
        migrations.RemoveField(
            model_name='high_class',
            name='attend_people',
        ),
        migrations.RemoveField(
            model_name='high_class',
            name='teach_teacher_email',
        ),
        migrations.AlterField(
            model_name='high_class',
            name='teach_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='老師'),
        ),
        migrations.CreateModel(
            name='Attend_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_password', models.CharField(max_length=10, verbose_name='參加密碼')),
                ('attend_number', models.IntegerField(default=0, verbose_name='參加人數')),
                ('attend_people', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='參加的人')),
            ],
        ),
        migrations.AddField(
            model_name='high_class',
            name='attend_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='public_class_high.Attend_data', verbose_name='參加資料'),
            preserve_default=False,
        ),
    ]
