# Generated by Django 2.2.3 on 2019-07-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0006_auto_20190723_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_class',
            name='attend_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='the_class', to='public_class_high.Attend_data', verbose_name='參加資料'),
        ),
    ]
