# Generated by Django 2.2.3 on 2019-07-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_high', '0007_auto_20190723_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='high_class',
            name='teaching_photo',
            field=models.URLField(default='', verbose_name='上課照片'),
        ),
    ]
