# Generated by Django 2.2.3 on 2019-07-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_department',
            field=models.CharField(max_length=3, verbose_name='老師教的部門'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_name',
            field=models.CharField(max_length=6, verbose_name='老師名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_subject',
            field=models.CharField(max_length=10, verbose_name='老師教的科目'),
        ),
    ]
