# Generated by Django 2.2.3 on 2019-07-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190723_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.BooleanField(default=False, verbose_name='管理員'),
        ),
    ]
