# Generated by Django 2.2.2 on 2019-07-07 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_teacher', models.CharField(max_length=6)),
                ('observer', models.TextField()),
                ('briefing_date', models.DateField()),
                ('briefing_time', models.TimeField()),
                ('advantages_and_features', models.TextField()),
                ('adjust_or_change', models.TextField()),
                ('learning_and_harvesting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Design_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('teach_teacher', models.CharField(max_length=6)),
                ('teach_class', models.CharField(max_length=20)),
                ('teaching_objectives', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_teacher', models.CharField(max_length=6)),
                ('teach_teacher_email', models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('class_room', models.CharField(max_length=10)),
                ('teach_date', models.DateField()),
                ('teach_start_time', models.TimeField()),
                ('teach_end_time', models.TimeField()),
                ('attend_password', models.CharField(max_length=10)),
                ('attend_number', models.IntegerField(default=0)),
                ('attend_people', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_date', models.DateField()),
                ('teach_start_time', models.TimeField()),
                ('teach_end_time', models.TimeField()),
                ('teaching_grade', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('teaching_sessions', models.IntegerField()),
                ('teach_teacher', models.CharField(max_length=6)),
                ('source_of_teaching_material', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('teaching_objectives', models.TextField()),
                ('student_experience', models.TextField()),
                ('teaching_activity', models.TextField()),
                ('evaluation_method', models.TextField()),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class')),
            ],
        ),
        migrations.CreateModel(
            name='Observation_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('author', models.CharField(max_length=6)),
                ('observation_date', models.DateField()),
                ('teach_teacher', models.CharField(max_length=6)),
                ('subject', models.CharField(max_length=20)),
                ('teach_class', models.CharField(max_length=20)),
                ('teaching_strategy_1', models.IntegerField()),
                ('teaching_strategy_1_text', models.TextField()),
                ('teaching_strategy_2', models.IntegerField()),
                ('teaching_strategy_2_text', models.TextField()),
                ('teaching_strategy_3', models.IntegerField()),
                ('teaching_strategy_3_text', models.TextField()),
                ('teaching_strategy_4', models.IntegerField()),
                ('teaching_strategy_4_text', models.TextField()),
                ('classroom_management_1', models.IntegerField()),
                ('classroom_management_1_text', models.TextField()),
                ('classroom_management_2', models.IntegerField()),
                ('classroom_management_2_text', models.TextField()),
                ('classroom_management_3', models.IntegerField()),
                ('classroom_management_3_text', models.TextField()),
                ('classroom_management_4', models.IntegerField()),
                ('classroom_management_4_text', models.TextField()),
                ('presenting_1', models.IntegerField()),
                ('presenting_1_text', models.TextField()),
                ('presenting_2', models.IntegerField()),
                ('presenting_2_text', models.TextField()),
                ('presenting_3', models.IntegerField()),
                ('presenting_3_text', models.TextField()),
                ('presenting_4', models.IntegerField()),
                ('presenting_4_text', models.TextField()),
                ('learning_environment_1', models.IntegerField()),
                ('learning_environment_1_text', models.TextField()),
                ('learning_environment_2', models.IntegerField()),
                ('learning_environment_2_text', models.TextField()),
                ('learning_environment_3', models.IntegerField()),
                ('learning_environment_3_text', models.TextField()),
                ('learning_environment_4', models.IntegerField()),
                ('learning_environment_4_text', models.TextField()),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class')),
            ],
        ),
        migrations.CreateModel(
            name='Growth_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_mode', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=50)),
                ('member', models.TextField()),
                ('done_date', models.DateField()),
                ('the_briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Briefing_record')),
            ],
        ),
        migrations.CreateModel(
            name='Design_table_datail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_activity', models.TextField()),
                ('teaching_aid', models.TextField()),
                ('assessment_method', models.TextField()),
                ('teaching_method', models.TextField()),
                ('time_allocation', models.TextField()),
                ('the_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Design_table')),
            ],
        ),
        migrations.AddField(
            model_name='design_table',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class'),
        ),
        migrations.AddField(
            model_name='briefing_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class'),
        ),
    ]
