# Generated by Django 2.2.3 on 2019-07-23 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_class_secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefing_record',
            options={'verbose_name': '國中共同議課紀錄表', 'verbose_name_plural': '國中共同議課紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='design_table',
            options={'verbose_name': '國中課程教學活動設計表', 'verbose_name_plural': '國中課程教學活動設計表'},
        ),
        migrations.AlterModelOptions(
            name='design_table_datail',
            options={'verbose_name': '國中課程教學活動設計表下方表格', 'verbose_name_plural': '國中課程教學活動設計表下方表格'},
        ),
        migrations.AlterModelOptions(
            name='growth_plan',
            options={'verbose_name': '授課教師預定專業成長計畫', 'verbose_name_plural': '授課教師預定專業成長計畫'},
        ),
        migrations.AlterModelOptions(
            name='observation_record',
            options={'verbose_name': '國中公開觀課紀錄表', 'verbose_name_plural': '國中公開觀課紀錄表'},
        ),
        migrations.AlterModelOptions(
            name='preparation_record',
            options={'verbose_name': '國中共同備課記錄表', 'verbose_name_plural': '國中共同備課記錄表'},
        ),
        migrations.AlterModelOptions(
            name='secondary_class',
            options={'verbose_name': '國中公開觀課報名資料', 'verbose_name_plural': '國中公開觀課報名資料'},
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='adjust_or_change',
            field=models.TextField(verbose_name='教與學待調整或改變之處'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='advantages_and_features',
            field=models.TextField(verbose_name='教與學之優點及特色'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='briefing_date',
            field=models.DateField(verbose_name='議課日期'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='briefing_time',
            field=models.TimeField(verbose_name='議課時間'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='learning_and_harvesting',
            field=models.TextField(verbose_name='回饋人員的學習與收穫'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='observer',
            field=models.TextField(verbose_name='觀察者'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='briefing_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='單元名稱'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_class',
            field=models.CharField(max_length=20, verbose_name='授課班級'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='授課老師'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='teaching_objectives',
            field=models.TextField(verbose_name='教學目標'),
        ),
        migrations.AlterField(
            model_name='design_table',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='assessment_method',
            field=models.TextField(verbose_name='評量方式'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_activity',
            field=models.TextField(verbose_name='教學活動'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_aid',
            field=models.TextField(verbose_name='使用教具'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='teaching_method',
            field=models.TextField(verbose_name='教學方法'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='the_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Design_table', verbose_name='課程教學活動設計表'),
        ),
        migrations.AlterField(
            model_name='design_table_datail',
            name='time_allocation',
            field=models.TextField(verbose_name='時間分配'),
        ),
        migrations.AlterField(
            model_name='growth_plan',
            name='abstract',
            field=models.CharField(max_length=50, verbose_name='內容概要說明'),
        ),
        migrations.AlterField(
            model_name='growth_plan',
            name='done_date',
            field=models.DateField(verbose_name='預計完成日期'),
        ),
        migrations.AlterField(
            model_name='growth_plan',
            name='growth_mode',
            field=models.CharField(max_length=50, verbose_name='成長方式'),
        ),
        migrations.AlterField(
            model_name='growth_plan',
            name='member',
            field=models.TextField(verbose_name='協助或合作人員'),
        ),
        migrations.AlterField(
            model_name='growth_plan',
            name='the_briefing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Briefing_record', verbose_name='議課紀錄表'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='author',
            field=models.CharField(max_length=6, verbose_name='填表人'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_1',
            field=models.IntegerField(verbose_name='善用有助於教學的管理步驟與常規-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_1_text',
            field=models.TextField(verbose_name='善用有助於教學的管理步驟與常規-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_2',
            field=models.IntegerField(verbose_name='能進行適當有序的教學活動，能調整上課速度-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_2_text',
            field=models.TextField(verbose_name='能進行適當有序的教學活動，能調整上課速度-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_3',
            field=models.IntegerField(verbose_name='將重點放在教學目標上並掌握學生的注意力-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_3_text',
            field=models.TextField(verbose_name='將重點放在教學目標上並掌握學生的注意力-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_4',
            field=models.IntegerField(verbose_name='妥善處理學生不當行為-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='classroom_management_4_text',
            field=models.TextField(verbose_name='妥善處理學生不當行為-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='context',
            field=models.TextField(verbose_name='摘記'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_1',
            field=models.IntegerField(verbose_name='給予學生適當的挑戰-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_1_text',
            field=models.TextField(verbose_name='給予學生適當的挑戰-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_2',
            field=models.IntegerField(verbose_name='教師在教學中表現熱忱、給予學生關切、鼓勵學生表達-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_2_text',
            field=models.TextField(verbose_name='教師在教學中表現熱忱、給予學生關切、鼓勵學生表達-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_3',
            field=models.IntegerField(verbose_name='形成積極參與的學習氣氛、引導合作學習的同儕互動關係-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_3_text',
            field=models.TextField(verbose_name='形成積極參與的學習氣氛、引導合作學習的同儕互動關係-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_4',
            field=models.IntegerField(verbose_name='建立互信相互尊重的班級氣氛-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='learning_environment_4_text',
            field=models.TextField(verbose_name=' 建立互信相互尊重的班級氣氛-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='observation_date',
            field=models.DateField(verbose_name='觀課日期'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_1',
            field=models.IntegerField(verbose_name='循序漸進由簡而繁有組織的呈現教材內容-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_1_text',
            field=models.TextField(verbose_name='循序漸進由簡而繁有組織的呈現教材內容-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_2',
            field=models.IntegerField(verbose_name='運用概念、定義、例證說明-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_2_text',
            field=models.TextField(verbose_name='運用概念、定義、例證說明-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_3',
            field=models.IntegerField(verbose_name='依據教學需要適切的運用教學媒體-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_3_text',
            field=models.TextField(verbose_name='依據教學需要適切的運用教學媒體-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_4',
            field=models.IntegerField(verbose_name='適切提供練習或作業，引導學生精熟學習-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='presenting_4_text',
            field=models.TextField(verbose_name='適切提供練習或作業，引導學生精熟學習-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teach_class',
            field=models.CharField(max_length=20, verbose_name='觀課班級'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='授課教師'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_1',
            field=models.IntegerField(verbose_name='要求學生參與教學活動-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_1_text',
            field=models.TextField(verbose_name='要求學生參與教學活動-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_2',
            field=models.IntegerField(verbose_name='延伸學生的反應或表現-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_2_text',
            field=models.TextField(verbose_name='延伸學生的反應或表現-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_3',
            field=models.IntegerField(verbose_name='在學習活動進行中掌握學生的表現-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_3_text',
            field=models.TextField(verbose_name='在學習活動進行中掌握學生的表現-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_4',
            field=models.IntegerField(verbose_name='提供正確的回饋或修正，澄清學生錯誤的觀念-量化結果'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='teaching_strategy_4_text',
            field=models.TextField(verbose_name='提供正確的回饋或修正，澄清學生錯誤的觀念-質性描述'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='教學單元'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='content',
            field=models.TextField(verbose_name='教材內容'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='evaluation_method',
            field=models.TextField(verbose_name='學生學習成效評估方式'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='source_of_teaching_material',
            field=models.CharField(max_length=20, verbose_name='教材來源'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='student_experience',
            field=models.TextField(verbose_name='學生經驗或學習背景分析'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_date',
            field=models.DateField(verbose_name='教學日期'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_end_time',
            field=models.TimeField(verbose_name='教學結束時間'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_start_time',
            field=models.TimeField(verbose_name='教學開始時間'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='教學者'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_activity',
            field=models.TextField(verbose_name='教學活動'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_grade',
            field=models.CharField(max_length=20, verbose_name='教學年級'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_objectives',
            field=models.TextField(verbose_name='教學目標'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='teaching_sessions',
            field=models.IntegerField(verbose_name='教學節數'),
        ),
        migrations.AlterField(
            model_name='preparation_record',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_class_secondary.Secondary_Class', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='attend_number',
            field=models.IntegerField(default=0, verbose_name='參加人數'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='attend_password',
            field=models.CharField(max_length=10, verbose_name='參加密碼'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='attend_people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='參加的人'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='class_room',
            field=models.CharField(max_length=10, verbose_name='上課教室'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='上課科目'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_date',
            field=models.DateField(verbose_name='上課日期'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_end_time',
            field=models.TimeField(verbose_name='上課結束時間'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_start_time',
            field=models.TimeField(verbose_name='上課開始時間'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_teacher',
            field=models.CharField(max_length=6, verbose_name='老師名字'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_teacher_email',
            field=models.EmailField(default='example@ttsh.tp.edu.tw', max_length=254, verbose_name='老師信箱'),
        ),
    ]
