# Generated by Django 2.2.3 on 2019-07-29 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_class_secondary', '0002_auto_20190723_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondary_class',
            name='attend_number',
        ),
        migrations.RemoveField(
            model_name='secondary_class',
            name='attend_password',
        ),
        migrations.RemoveField(
            model_name='secondary_class',
            name='attend_people',
        ),
        migrations.RemoveField(
            model_name='secondary_class',
            name='teach_teacher_email',
        ),
        migrations.AddField(
            model_name='secondary_class',
            name='teaching_photo',
            field=models.URLField(default='', verbose_name='上課照片'),
        ),
        migrations.AlterField(
            model_name='observation_record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_observation', to=settings.AUTH_USER_MODEL, verbose_name='填表人'),
        ),
        migrations.AlterField(
            model_name='secondary_class',
            name='teach_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='老師'),
        ),
        migrations.CreateModel(
            name='Attend_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_password', models.CharField(max_length=10, verbose_name='參加密碼')),
                ('attend_number', models.IntegerField(default=0, verbose_name='參加人數')),
                ('attend_people', models.ManyToManyField(related_name='attend_class', to=settings.AUTH_USER_MODEL, verbose_name='參加的人')),
            ],
            options={
                'verbose_name': '國中公開觀課報名人數',
                'verbose_name_plural': '國中公開觀課報名人數',
            },
        ),
        migrations.AddField(
            model_name='secondary_class',
            name='attend_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='the_class', to='public_class_secondary.Attend_data', verbose_name='參加資料'),
            preserve_default=False,
        ),
    ]
